-- PRAY ON anonymous prayer box
create table if not exists public.anonymous_prayers (
  id bigint generated by default as identity primary key,
  content text not null check (char_length(content) between 1 and 1000),
  source text not null default 'prayon-web',
  created_at timestamptz not null default now(),
  reviewed_at timestamptz,
  is_archived boolean not null default false
);

alter table public.anonymous_prayers enable row level security;

revoke all on table public.anonymous_prayers from anon, authenticated;
grant insert on table public.anonymous_prayers to anon, authenticated;
grant usage, select on sequence public.anonymous_prayers_id_seq to anon, authenticated;

drop policy if exists "allow anonymous prayer submission" on public.anonymous_prayers;
create policy "allow anonymous prayer submission"
on public.anonymous_prayers
for insert
to anon, authenticated
with check (
  char_length(content) between 1 and 1000
  and source = 'prayon-web'
);

-- Deliberately no SELECT policy:
-- website visitors can submit but cannot read anyone else's prayer.
