-- PRAY ON v21 — private personal journal and print-quality photos
-- 기존 익명 기도함과 주간 메시지 데이터는 변경하지 않습니다.

create table if not exists public.personal_journal_entries (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  entry_date date not null,
  weekly_content_id bigint references public.weekly_content(id) on delete set null,
  first_title_snapshot text,
  second_title_snapshot text,
  content text not null check (char_length(content) between 1 and 5000),
  image_master_path text,
  image_thumb_path text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(user_id, entry_date)
);

create index if not exists idx_personal_journal_user_date
  on public.personal_journal_entries(user_id, entry_date desc);

alter table public.personal_journal_entries enable row level security;

grant select, insert, update, delete
  on table public.personal_journal_entries
  to authenticated;

grant usage, select on all sequences in schema public to authenticated;

do $policies$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname='public'
      and tablename='personal_journal_entries'
      and policyname='users read own journal'
  ) then
    execute $policy$
      create policy "users read own journal"
      on public.personal_journal_entries
      for select
      to authenticated
      using (user_id = auth.uid())
    $policy$;
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname='public'
      and tablename='personal_journal_entries'
      and policyname='users insert own journal'
  ) then
    execute $policy$
      create policy "users insert own journal"
      on public.personal_journal_entries
      for insert
      to authenticated
      with check (user_id = auth.uid())
    $policy$;
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname='public'
      and tablename='personal_journal_entries'
      and policyname='users update own journal'
  ) then
    execute $policy$
      create policy "users update own journal"
      on public.personal_journal_entries
      for update
      to authenticated
      using (user_id = auth.uid())
      with check (user_id = auth.uid())
    $policy$;
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname='public'
      and tablename='personal_journal_entries'
      and policyname='users delete own journal'
  ) then
    execute $policy$
      create policy "users delete own journal"
      on public.personal_journal_entries
      for delete
      to authenticated
      using (user_id = auth.uid())
    $policy$;
  end if;
end
$policies$;

insert into storage.buckets (
  id,
  name,
  public,
  file_size_limit,
  allowed_mime_types
)
values (
  'private-journal',
  'private-journal',
  false,
  15728640,
  array['image/jpeg','image/png','image/webp']
)
on conflict (id) do update set
  public = false,
  file_size_limit = 15728640,
  allowed_mime_types = array['image/jpeg','image/png','image/webp'];

do $storage_policies$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname='storage'
      and tablename='objects'
      and policyname='users read own journal photos'
  ) then
    execute $policy$
      create policy "users read own journal photos"
      on storage.objects
      for select
      to authenticated
      using (
        bucket_id = 'private-journal'
        and (storage.foldername(name))[1] = auth.uid()::text
      )
    $policy$;
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname='storage'
      and tablename='objects'
      and policyname='users upload own journal photos'
  ) then
    execute $policy$
      create policy "users upload own journal photos"
      on storage.objects
      for insert
      to authenticated
      with check (
        bucket_id = 'private-journal'
        and (storage.foldername(name))[1] = auth.uid()::text
      )
    $policy$;
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname='storage'
      and tablename='objects'
      and policyname='users update own journal photos'
  ) then
    execute $policy$
      create policy "users update own journal photos"
      on storage.objects
      for update
      to authenticated
      using (
        bucket_id = 'private-journal'
        and (storage.foldername(name))[1] = auth.uid()::text
      )
      with check (
        bucket_id = 'private-journal'
        and (storage.foldername(name))[1] = auth.uid()::text
      )
    $policy$;
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname='storage'
      and tablename='objects'
      and policyname='users delete own journal photos'
  ) then
    execute $policy$
      create policy "users delete own journal photos"
      on storage.objects
      for delete
      to authenticated
      using (
        bucket_id = 'private-journal'
        and (storage.foldername(name))[1] = auth.uid()::text
      )
    $policy$;
  end if;
end
$storage_policies$;
