-- PRAY ON v11 patch
-- Run this entire file in Supabase > SQL Editor.

-- Public list: visitors may read only non-archived prayers.
grant select on table public.anonymous_prayers to anon, authenticated;

drop policy if exists "public can read active anonymous prayers"
on public.anonymous_prayers;

create policy "public can read active anonymous prayers"
on public.anonymous_prayers
for select
to anon, authenticated
using (is_archived = false);

-- Report storage. Reports are not publicly readable.
create table if not exists public.prayer_reports (
  id bigint generated by default as identity primary key,
  prayer_id bigint not null references public.anonymous_prayers(id) on delete cascade,
  source text not null default 'public-list',
  created_at timestamptz not null default now()
);

create index if not exists idx_prayer_reports_prayer_id
  on public.prayer_reports(prayer_id, created_at desc);

alter table public.prayer_reports enable row level security;

revoke all on table public.prayer_reports from anon, authenticated;
grant insert on table public.prayer_reports to anon, authenticated;
grant select, delete on table public.prayer_reports to authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

drop policy if exists "anyone can report a prayer"
on public.prayer_reports;

create policy "anyone can report a prayer"
on public.prayer_reports
for insert
to anon, authenticated
with check (
  source = 'public-list'
  and exists (
    select 1
    from public.anonymous_prayers p
    where p.id = prayer_id
      and p.is_archived = false
  )
);

drop policy if exists "admins can read prayer reports"
on public.prayer_reports;

create policy "admins can read prayer reports"
on public.prayer_reports
for select
to authenticated
using (public.is_admin());

drop policy if exists "admins can delete prayer reports"
on public.prayer_reports;

create policy "admins can delete prayer reports"
on public.prayer_reports
for delete
to authenticated
using (public.is_admin());
