-- PRAY ON v19 — service links, titles, scriptures, and Mon-Sat prayer cards
-- Existing anonymous prayers and reactions are not changed.

alter table public.weekly_content
  add column if not exists first_title text,
  add column if not exists first_scripture text,
  add column if not exists first_youtube_url text,
  add column if not exists second_title text,
  add column if not exists second_scripture text,
  add column if not exists second_youtube_url text,
  add column if not exists middle_title text,
  add column if not exists middle_scripture text,
  add column if not exists middle_youtube_url text,
  add column if not exists high_title text,
  add column if not exists high_scripture text,
  add column if not exists high_youtube_url text,
  add column if not exists first_pdf_url text,
  add column if not exists second_pdf_url text,
  add column if not exists mon_excerpt text,
  add column if not exists mon_prayer text,
  add column if not exists tue_excerpt text,
  add column if not exists tue_prayer text,
  add column if not exists wed_excerpt text,
  add column if not exists wed_prayer text,
  add column if not exists thu_excerpt text,
  add column if not exists thu_prayer text,
  add column if not exists fri_excerpt text,
  add column if not exists fri_prayer text,
  add column if not exists sat_excerpt text,
  add column if not exists sat_prayer text;

insert into public.weekly_content (
  message_date,
  service_label,
  message_title,
  scripture,
  first_title,
  first_scripture,
  first_youtube_url,
  second_title,
  second_scripture,
  second_youtube_url,
  middle_title,
  middle_scripture,
  middle_youtube_url,
  high_title,
  high_scripture,
  high_youtube_url,
  first_pdf_url,
  second_pdf_url,
  key_sentence,
  daily_prayer,
  mon_excerpt,
  mon_prayer,
  tue_excerpt,
  tue_prayer,
  wed_excerpt,
  wed_prayer,
  thu_excerpt,
  thu_prayer,
  fri_excerpt,
  fri_prayer,
  sat_excerpt,
  sat_prayer,
  prayer_worry,
  prayer_hurt,
  prayer_anger,
  prayer_courage,
  prayer_thanks,
  prayer_friend,
  is_published,
  updated_at
)
values (
  date '2026-07-26',
  '주일 1부 예배',
  '렘넌트 서밋의 길',
  '빌립보서 3:1-16',
  '렘넌트 서밋의 길',
  '빌립보서 3:1-16',
  'https://youtu.be/4tL4ZPHEelM?si=rsF4aGK4ti0x0VEY',
  '초대교회의 대형 사건',
  '사도행전 3:1-12',
  'https://youtu.be/AsLgutmp-q0?si=8ekqwBOU5U-wsp0p',
  '24통하는 무전기',
  '에베소서 6:18',
  'https://youtu.be/ZlX5eLp_6Qo?si=gdPneNLOf9ZXO_43',
  '고등부 연합 기도회',
  '2026년 7월 26일',
  'https://youtu.be/KVEMegOW7RU?si=6cR9nKIdkcb2s7x6',
  'assets/20260726_1ST_Garo_KR.pdf',
  'assets/20260726_2ND_Garo_KR.pdf',
  'Power, Talent, Mission을 질문하며 하나님이 준비하신 렘넌트 서밋의 길을 시작해요.',
  '하나님, 이번 주 말씀을 제 삶에 연결하고 아침·낮·밤의 기도 속에서 나와 세상과 미래를 살리는 길을 걷게 해 주세요.',
  '나에게 필요한 능력은 무엇인가? 나의 달란트와 미션은 무엇인가?',
  '하나님, 오늘 제가 가져야 할 Heavenly Power와 보좌에서 주신 Talent, 그리고 하나님이 맡기신 Mission을 발견하게 해 주세요.',
  '큰 기적보다 중요한 것은 고통 속에서도 하나님의 계획을 본 믿음입니다.',
  '하나님, 눈에 보이는 결과보다 절대 언약을 믿는 믿음을 붙잡게 해 주세요. 위기 속에서도 하나님이 앞서 보내시고 함께하심을 믿게 해 주세요.',
  '아침에는 보좌의 망대, 낮에는 보좌의 여정, 밤에는 보좌의 이정표를 만들어요.',
  '하나님, 아침에는 나를 살리는 기도, 낮에는 만남 속에서 하나님의 비밀을 보는 눈, 밤에는 미래를 준비하는 작품을 남기게 해 주세요.',
  '나사렛 예수 그리스도의 이름으로 일어나 걸으라.',
  '하나님, 제 힘이 아니라 그리스도의 이름을 믿고 선포하게 해 주세요. 어두움 속에 빛을 전하고 낙심한 사람을 일으키는 믿음을 주세요.',
  '흔들려도 괜찮고 무너져도 괜찮아요. 다시 일어나면 됩니다.',
  '하나님, 흔들리고 넘어져도 포기하지 않고 다시 일어나게 해 주세요. 아침·낮·밤의 기도 속에서 망대와 여정과 이정표를 누리게 해 주세요.',
  '그리스도의 이름이 선포되면 빛이 전달되고 흑암이 꺾입니다.',
  '하나님, 그리스도의 이름을 믿음으로 붙잡게 해 주세요. 제가 가는 곳마다 빛이 비치고 사람을 살리는 증거가 나타나게 해 주세요.',
  '하나님, 흔들림과 갈등 속에서도 제가 길을 찾고 있음을 믿게 해 주세요. 보좌에서 주시는 힘으로 오늘의 문제를 이기게 해 주세요.',
  '하나님, 상처와 고통 속에도 하나님의 계획이 있음을 보게 해 주세요. 그리스도의 이름으로 제 마음을 일으켜 주세요.',
  '하나님, 감정과 사람의 말보다 언약을 먼저 붙잡게 해 주세요. 제 마음을 정복하고 사람을 살리는 선택을 하게 해 주세요.',
  '하나님, 나사렛 예수 그리스도의 이름을 믿고 담대하게 일어나 걷게 해 주세요.',
  '하나님, 제게 주신 Power와 Talent와 Mission을 감사로 발견하게 해 주세요.',
  '하나님, 친구와 학교에 그리스도의 빛이 비치게 하시고 제가 사람을 일으키는 믿음의 증인이 되게 해 주세요.',
  true,
  now()
)
on conflict (message_date)
do update set
  service_label=excluded.service_label,
  message_title=excluded.message_title,
  scripture=excluded.scripture,
  first_title=excluded.first_title,
  first_scripture=excluded.first_scripture,
  first_youtube_url=excluded.first_youtube_url,
  second_title=excluded.second_title,
  second_scripture=excluded.second_scripture,
  second_youtube_url=excluded.second_youtube_url,
  middle_title=excluded.middle_title,
  middle_scripture=excluded.middle_scripture,
  middle_youtube_url=excluded.middle_youtube_url,
  high_title=excluded.high_title,
  high_scripture=excluded.high_scripture,
  high_youtube_url=excluded.high_youtube_url,
  first_pdf_url=excluded.first_pdf_url,
  second_pdf_url=excluded.second_pdf_url,
  key_sentence=excluded.key_sentence,
  daily_prayer=excluded.daily_prayer,
  mon_excerpt=excluded.mon_excerpt,
  mon_prayer=excluded.mon_prayer,
  tue_excerpt=excluded.tue_excerpt,
  tue_prayer=excluded.tue_prayer,
  wed_excerpt=excluded.wed_excerpt,
  wed_prayer=excluded.wed_prayer,
  thu_excerpt=excluded.thu_excerpt,
  thu_prayer=excluded.thu_prayer,
  fri_excerpt=excluded.fri_excerpt,
  fri_prayer=excluded.fri_prayer,
  sat_excerpt=excluded.sat_excerpt,
  sat_prayer=excluded.sat_prayer,
  prayer_worry=excluded.prayer_worry,
  prayer_hurt=excluded.prayer_hurt,
  prayer_anger=excluded.prayer_anger,
  prayer_courage=excluded.prayer_courage,
  prayer_thanks=excluded.prayer_thanks,
  prayer_friend=excluded.prayer_friend,
  is_published=true,
  updated_at=now();
