-- ============================================================
-- PRAY ON v9 — Supabase schema, RLS, admin moderation
-- Run this entire file in Supabase > SQL Editor.
-- ============================================================

-- 1. User profiles and admin role
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  role text not null default 'member' check (role in ('member', 'admin')),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email)
  values (new.id, new.email)
  on conflict (id) do update
    set email = excluded.email,
        updated_at = now();
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert or update of email on auth.users
for each row execute function public.handle_new_user();

-- Backfill users that existed before this trigger.
insert into public.profiles (id, email)
select id, email from auth.users
on conflict (id) do update
  set email = excluded.email,
      updated_at = now();

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles
    where id = auth.uid()
      and role = 'admin'
      and is_active = true
  );
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to authenticated;

-- 2. Anonymous prayer box
create table if not exists public.anonymous_prayers (
  id bigint generated by default as identity primary key,
  content text not null check (char_length(content) between 1 and 1000),
  source text not null default 'prayon-web',
  created_at timestamptz not null default now(),
  reviewed_at timestamptz,
  is_archived boolean not null default false
);

-- Add columns if an older table already existed.
alter table public.anonymous_prayers
  add column if not exists source text not null default 'prayon-web',
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists reviewed_at timestamptz,
  add column if not exists is_archived boolean not null default false;

-- 3. Weekly messages
create table if not exists public.weekly_messages (
  id bigint generated by default as identity primary key,
  service_type text not null default 'first',
  title text not null,
  scripture text,
  summary text,
  youtube_url text,
  pdf_url text,
  message_date date not null,
  is_published boolean not null default false,
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- 4. Prayer cards
create table if not exists public.prayer_cards (
  id bigint generated by default as identity primary key,
  weekly_message_id bigint references public.weekly_messages(id) on delete set null,
  title text,
  key_sentence text not null,
  prayer_text text,
  image_url text,
  card_date date,
  is_published boolean not null default false,
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- 5. Personal prayer records (for future member login)
create table if not exists public.my_prayers (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  held_sentence text,
  prayer_text text,
  prayer_date date not null default current_date,
  is_answered boolean not null default false,
  answered_note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_anonymous_prayers_created_at
  on public.anonymous_prayers (created_at desc);
create index if not exists idx_my_prayers_user_date
  on public.my_prayers (user_id, prayer_date desc);
create index if not exists idx_weekly_messages_date
  on public.weekly_messages (message_date desc);

-- 6. Enable RLS
alter table public.profiles enable row level security;
alter table public.anonymous_prayers enable row level security;
alter table public.weekly_messages enable row level security;
alter table public.prayer_cards enable row level security;
alter table public.my_prayers enable row level security;

-- 7. Minimum grants for the Data API
revoke all on table public.profiles from anon, authenticated;
revoke all on table public.anonymous_prayers from anon, authenticated;
revoke all on table public.weekly_messages from anon, authenticated;
revoke all on table public.prayer_cards from anon, authenticated;
revoke all on table public.my_prayers from anon, authenticated;

grant select on table public.profiles to authenticated;

grant insert on table public.anonymous_prayers to anon, authenticated;
grant select, update, delete on table public.anonymous_prayers to authenticated;

grant select on table public.weekly_messages to anon, authenticated;
grant insert, update, delete on table public.weekly_messages to authenticated;

grant select on table public.prayer_cards to anon, authenticated;
grant insert, update, delete on table public.prayer_cards to authenticated;

grant select, insert, update, delete on table public.my_prayers to authenticated;

grant usage, select on all sequences in schema public to anon, authenticated;

-- 8. Profiles policies
drop policy if exists "users can read own profile" on public.profiles;
create policy "users can read own profile"
on public.profiles for select
to authenticated
using (id = auth.uid() or public.is_admin());

-- 9. Anonymous prayer policies
drop policy if exists "anyone can submit anonymous prayer" on public.anonymous_prayers;
create policy "anyone can submit anonymous prayer"
on public.anonymous_prayers for insert
to anon, authenticated
with check (
  char_length(content) between 1 and 1000
  and source = 'prayon-web'
);

drop policy if exists "admins can read anonymous prayers" on public.anonymous_prayers;
create policy "admins can read anonymous prayers"
on public.anonymous_prayers for select
to authenticated
using (public.is_admin());

drop policy if exists "admins can update anonymous prayers" on public.anonymous_prayers;
create policy "admins can update anonymous prayers"
on public.anonymous_prayers for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "admins can delete anonymous prayers" on public.anonymous_prayers;
create policy "admins can delete anonymous prayers"
on public.anonymous_prayers for delete
to authenticated
using (public.is_admin());

-- 10. Weekly content policies
drop policy if exists "public can read published weekly messages" on public.weekly_messages;
create policy "public can read published weekly messages"
on public.weekly_messages for select
to anon, authenticated
using (is_published = true or public.is_admin());

drop policy if exists "admins can insert weekly messages" on public.weekly_messages;
create policy "admins can insert weekly messages"
on public.weekly_messages for insert
to authenticated
with check (public.is_admin());

drop policy if exists "admins can update weekly messages" on public.weekly_messages;
create policy "admins can update weekly messages"
on public.weekly_messages for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "admins can delete weekly messages" on public.weekly_messages;
create policy "admins can delete weekly messages"
on public.weekly_messages for delete
to authenticated
using (public.is_admin());

drop policy if exists "public can read published prayer cards" on public.prayer_cards;
create policy "public can read published prayer cards"
on public.prayer_cards for select
to anon, authenticated
using (is_published = true or public.is_admin());

drop policy if exists "admins can insert prayer cards" on public.prayer_cards;
create policy "admins can insert prayer cards"
on public.prayer_cards for insert
to authenticated
with check (public.is_admin());

drop policy if exists "admins can update prayer cards" on public.prayer_cards;
create policy "admins can update prayer cards"
on public.prayer_cards for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "admins can delete prayer cards" on public.prayer_cards;
create policy "admins can delete prayer cards"
on public.prayer_cards for delete
to authenticated
using (public.is_admin());

-- 11. Personal prayer policies
drop policy if exists "users can read own prayers" on public.my_prayers;
create policy "users can read own prayers"
on public.my_prayers for select
to authenticated
using (user_id = auth.uid());

drop policy if exists "users can insert own prayers" on public.my_prayers;
create policy "users can insert own prayers"
on public.my_prayers for insert
to authenticated
with check (user_id = auth.uid());

drop policy if exists "users can update own prayers" on public.my_prayers;
create policy "users can update own prayers"
on public.my_prayers for update
to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

drop policy if exists "users can delete own prayers" on public.my_prayers;
create policy "users can delete own prayers"
on public.my_prayers for delete
to authenticated
using (user_id = auth.uid());

-- ============================================================
-- AFTER creating an admin user in Authentication > Users,
-- replace the email below and run ONLY this final statement:
--
-- update public.profiles
-- set role = 'admin', is_active = true, updated_at = now()
-- where lower(email) = lower('YOUR_ADMIN_EMAIL@example.com');
-- ============================================================

-- PRAY ON v11 patch
-- Run this entire file in Supabase > SQL Editor.

-- Public list: visitors may read only non-archived prayers.
grant select on table public.anonymous_prayers to anon, authenticated;

drop policy if exists "public can read active anonymous prayers"
on public.anonymous_prayers;

create policy "public can read active anonymous prayers"
on public.anonymous_prayers
for select
to anon, authenticated
using (is_archived = false);

-- Report storage. Reports are not publicly readable.
create table if not exists public.prayer_reports (
  id bigint generated by default as identity primary key,
  prayer_id bigint not null references public.anonymous_prayers(id) on delete cascade,
  source text not null default 'public-list',
  created_at timestamptz not null default now()
);

create index if not exists idx_prayer_reports_prayer_id
  on public.prayer_reports(prayer_id, created_at desc);

alter table public.prayer_reports enable row level security;

revoke all on table public.prayer_reports from anon, authenticated;
grant insert on table public.prayer_reports to anon, authenticated;
grant select, delete on table public.prayer_reports to authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

drop policy if exists "anyone can report a prayer"
on public.prayer_reports;

create policy "anyone can report a prayer"
on public.prayer_reports
for insert
to anon, authenticated
with check (
  source = 'public-list'
  and exists (
    select 1
    from public.anonymous_prayers p
    where p.id = prayer_id
      and p.is_archived = false
  )
);

drop policy if exists "admins can read prayer reports"
on public.prayer_reports;

create policy "admins can read prayer reports"
on public.prayer_reports
for select
to authenticated
using (public.is_admin());

drop policy if exists "admins can delete prayer reports"
on public.prayer_reports;

create policy "admins can delete prayer reports"
on public.prayer_reports
for delete
to authenticated
using (public.is_admin());

-- PRAY ON v13 — shared "기도했어요" glow
-- Run this entire file in Supabase > SQL Editor.

create table if not exists public.prayer_reactions (
  id bigint generated by default as identity primary key,
  prayer_id bigint not null references public.anonymous_prayers(id) on delete cascade,
  device_id uuid not null,
  reacted_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '12 hours'),
  unique (prayer_id, device_id),
  check (expires_at > reacted_at),
  check (expires_at <= reacted_at + interval '12 hours 5 minutes')
);

create index if not exists idx_prayer_reactions_active
  on public.prayer_reactions (prayer_id, expires_at desc);

alter table public.prayer_reactions enable row level security;

revoke all on table public.prayer_reactions from anon, authenticated;
grant select on table public.prayer_reactions to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

drop policy if exists "public can read active prayer reactions"
on public.prayer_reactions;

create policy "public can read active prayer reactions"
on public.prayer_reactions
for select
to anon, authenticated
using (expires_at > now());

create or replace function public.set_prayer_reaction(
  p_prayer_id bigint,
  p_device_id uuid,
  p_active boolean
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  -- Remove expired rows whenever the function is used.
  delete from public.prayer_reactions
  where expires_at <= now();

  if p_active then
    if not exists (
      select 1
      from public.anonymous_prayers
      where id = p_prayer_id
        and is_archived = false
    ) then
      raise exception 'Prayer not found or archived';
    end if;

    insert into public.prayer_reactions (
      prayer_id,
      device_id,
      reacted_at,
      expires_at
    )
    values (
      p_prayer_id,
      p_device_id,
      now(),
      now() + interval '12 hours'
    )
    on conflict (prayer_id, device_id)
    do update set
      reacted_at = excluded.reacted_at,
      expires_at = excluded.expires_at;
  else
    delete from public.prayer_reactions
    where prayer_id = p_prayer_id
      and device_id = p_device_id;
  end if;
end;
$$;

revoke all on function public.set_prayer_reaction(bigint, uuid, boolean) from public;
grant execute on function public.set_prayer_reaction(bigint, uuid, boolean)
  to anon, authenticated;

-- Enable Realtime publication once.
do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'prayer_reactions'
  ) then
    alter publication supabase_realtime add table public.prayer_reactions;
  end if;
end
$$;
