-- PRAY ON v13 — shared "기도했어요" glow
-- Run this entire file in Supabase > SQL Editor.

create table if not exists public.prayer_reactions (
  id bigint generated by default as identity primary key,
  prayer_id bigint not null references public.anonymous_prayers(id) on delete cascade,
  device_id uuid not null,
  reacted_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '12 hours'),
  unique (prayer_id, device_id),
  check (expires_at > reacted_at),
  check (expires_at <= reacted_at + interval '12 hours 5 minutes')
);

create index if not exists idx_prayer_reactions_active
  on public.prayer_reactions (prayer_id, expires_at desc);

alter table public.prayer_reactions enable row level security;

revoke all on table public.prayer_reactions from anon, authenticated;
grant select on table public.prayer_reactions to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

drop policy if exists "public can read active prayer reactions"
on public.prayer_reactions;

create policy "public can read active prayer reactions"
on public.prayer_reactions
for select
to anon, authenticated
using (expires_at > now());

create or replace function public.set_prayer_reaction(
  p_prayer_id bigint,
  p_device_id uuid,
  p_active boolean
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  -- Remove expired rows whenever the function is used.
  delete from public.prayer_reactions
  where expires_at <= now();

  if p_active then
    if not exists (
      select 1
      from public.anonymous_prayers
      where id = p_prayer_id
        and is_archived = false
    ) then
      raise exception 'Prayer not found or archived';
    end if;

    insert into public.prayer_reactions (
      prayer_id,
      device_id,
      reacted_at,
      expires_at
    )
    values (
      p_prayer_id,
      p_device_id,
      now(),
      now() + interval '12 hours'
    )
    on conflict (prayer_id, device_id)
    do update set
      reacted_at = excluded.reacted_at,
      expires_at = excluded.expires_at;
  else
    delete from public.prayer_reactions
    where prayer_id = p_prayer_id
      and device_id = p_device_id;
  end if;
end;
$$;

revoke all on function public.set_prayer_reaction(bigint, uuid, boolean) from public;
grant execute on function public.set_prayer_reaction(bigint, uuid, boolean)
  to anon, authenticated;

-- Enable Realtime publication once.
do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'prayer_reactions'
  ) then
    alter publication supabase_realtime add table public.prayer_reactions;
  end if;
end
$$;
